/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	autodeployv1 "github.com/alpha-supsys/go-crd-autodeployunits/k8s/group/apis/autodeploy/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAutoDeployUnits implements AutoDeployUnitInterface
type FakeAutoDeployUnits struct {
	Fake *FakeAutodeployV1
	ns   string
}

var autodeployunitsResource = schema.GroupVersionResource{Group: "autodeploy.alpha-supsys.com", Version: "v1", Resource: "autodeployunits"}

var autodeployunitsKind = schema.GroupVersionKind{Group: "autodeploy.alpha-supsys.com", Version: "v1", Kind: "AutoDeployUnit"}

// Get takes name of the autoDeployUnit, and returns the corresponding autoDeployUnit object, and an error if there is any.
func (c *FakeAutoDeployUnits) Get(ctx context.Context, name string, options v1.GetOptions) (result *autodeployv1.AutoDeployUnit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(autodeployunitsResource, c.ns, name), &autodeployv1.AutoDeployUnit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*autodeployv1.AutoDeployUnit), err
}

// List takes label and field selectors, and returns the list of AutoDeployUnits that match those selectors.
func (c *FakeAutoDeployUnits) List(ctx context.Context, opts v1.ListOptions) (result *autodeployv1.AutoDeployUnitList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(autodeployunitsResource, autodeployunitsKind, c.ns, opts), &autodeployv1.AutoDeployUnitList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &autodeployv1.AutoDeployUnitList{ListMeta: obj.(*autodeployv1.AutoDeployUnitList).ListMeta}
	for _, item := range obj.(*autodeployv1.AutoDeployUnitList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested autoDeployUnits.
func (c *FakeAutoDeployUnits) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(autodeployunitsResource, c.ns, opts))

}

// Create takes the representation of a autoDeployUnit and creates it.  Returns the server's representation of the autoDeployUnit, and an error, if there is any.
func (c *FakeAutoDeployUnits) Create(ctx context.Context, autoDeployUnit *autodeployv1.AutoDeployUnit, opts v1.CreateOptions) (result *autodeployv1.AutoDeployUnit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(autodeployunitsResource, c.ns, autoDeployUnit), &autodeployv1.AutoDeployUnit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*autodeployv1.AutoDeployUnit), err
}

// Update takes the representation of a autoDeployUnit and updates it. Returns the server's representation of the autoDeployUnit, and an error, if there is any.
func (c *FakeAutoDeployUnits) Update(ctx context.Context, autoDeployUnit *autodeployv1.AutoDeployUnit, opts v1.UpdateOptions) (result *autodeployv1.AutoDeployUnit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(autodeployunitsResource, c.ns, autoDeployUnit), &autodeployv1.AutoDeployUnit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*autodeployv1.AutoDeployUnit), err
}

// Delete takes name of the autoDeployUnit and deletes it. Returns an error if one occurs.
func (c *FakeAutoDeployUnits) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(autodeployunitsResource, c.ns, name), &autodeployv1.AutoDeployUnit{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAutoDeployUnits) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(autodeployunitsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &autodeployv1.AutoDeployUnitList{})
	return err
}

// Patch applies the patch and returns the patched autoDeployUnit.
func (c *FakeAutoDeployUnits) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *autodeployv1.AutoDeployUnit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(autodeployunitsResource, c.ns, name, pt, data, subresources...), &autodeployv1.AutoDeployUnit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*autodeployv1.AutoDeployUnit), err
}
