/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	autodeployv1 "github.com/alpha-supsys/go-crd-autodeployunits/k8s/group/apis/autodeploy/v1"
	versioned "github.com/alpha-supsys/go-crd-autodeployunits/k8s/group/client/clientset/versioned"
	internalinterfaces "github.com/alpha-supsys/go-crd-autodeployunits/k8s/group/client/informers/externalversions/internalinterfaces"
	v1 "github.com/alpha-supsys/go-crd-autodeployunits/k8s/group/client/listers/autodeploy/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AutoDeployUnitInformer provides access to a shared informer and lister for
// AutoDeployUnits.
type AutoDeployUnitInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.AutoDeployUnitLister
}

type autoDeployUnitInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAutoDeployUnitInformer constructs a new informer for AutoDeployUnit type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAutoDeployUnitInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAutoDeployUnitInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAutoDeployUnitInformer constructs a new informer for AutoDeployUnit type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAutoDeployUnitInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AutodeployV1().AutoDeployUnits(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AutodeployV1().AutoDeployUnits(namespace).Watch(context.TODO(), options)
			},
		},
		&autodeployv1.AutoDeployUnit{},
		resyncPeriod,
		indexers,
	)
}

func (f *autoDeployUnitInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAutoDeployUnitInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *autoDeployUnitInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&autodeployv1.AutoDeployUnit{}, f.defaultInformer)
}

func (f *autoDeployUnitInformer) Lister() v1.AutoDeployUnitLister {
	return v1.NewAutoDeployUnitLister(f.Informer().GetIndexer())
}
